### ISSUE TITLE
[7.0] Installation error

### ISSUE THREAD

**Issue by kenvac** [Kranbery/Avalara-Avatax-Odoo-7.0#1]
Hi.

We are getting errors during installation process. We are on version 7.0

```
AttributeError: View definition error for inherited view '' on model 'account.invoice': Element '<button name="button_reset_taxes" states="draft,proforma2" string="(update)" class="oe_link oe_edit_only" type="object" help="Recompute taxes and total">' not found in parent view 'account.invoice_form'
2014-07-28 12:00:52,291 30466 ERROR faction_20140728 openerp.tools.convert: Parse error in /home/kinner/workspace/openerp/7.0/avatax/avalara_salestax/account_invoice_view.xml:6: 
<record id="invoice_form_inherit_1" model="ir.ui.view">
            <field name="name">account.invoice.form.inherit</field>
            <field name="model">account.invoice</field>
            <field name="inherit_id" ref="account.invoice_form"/>
            <field name="type">form</field>
            <field name="arch" type="xml">

                <data><field name="type" position="after">
                    <div class="oe_right oe_button_box">
                        <button name="button_dummy" states="draft" string="Compute" type="object" icon="gtk-execute" class="oe_highlight"/>
                    </div>
                </field>
                <field name="payment_term" position="after">
                    <field name="invoice_doc_no" attrs="{'required': [('type','=','out_refund')],'invisible': [('type','!=','out_refund')]}"/>
                </field>
                <xpath expr="/form/sheet/notebook/page[@string='Invoice Lines']/field[@name='invoice_line']/tree/field[@name='price_unit']" position="before">
                    <field name="tax_amt" readonly="1" groups="avalara_salestax.group_avatax_view"/>
                </xpath>

                <field name="invoice_line" position="after">
                    <h3><label style="color: #7c7bad;" for="shipping_lines"/></h3>
                    <field name="shipping_lines">
                        <tree string="Shipping Order Lines" editable="bottom">
                              <field name="ship_method_id" on_change="onchange_select(ship_method_id)"/>
                              <field name="ship_code_id" domain="[('type', '=', 'freight')]" context="{'search_default_type': 'freight', 'default_type': 'freight'}"/>
                              <field name="tax_amt" readonly="1" groups="avalara_salestax.group_avatax_view"/>
                              <field name="shipping_cost"/>
                              <field name="sale_account_id" invisible="1"/>
                        </tree>
                    </field>
                </field>

                <field name="amount_untaxed" position="replace">
                    <field name="amount_untaxed" string="Net Total"/>
                    <field name="shipping_amt"/>
                </field>

                <xpath expr="/form/sheet/group/group/field[@name='account_id']" position="after">
                    <field name="exemption_code" readonly="1"/>
                    <field name="exemption_code_id" readonly="1"/>
                    <field name="location_code" readonly="1"/>
                    <field name="is_add_validate" readonly="1" invisible="1"/>
                </xpath>

                                <button name="button_reset_taxes" states="draft,proforma2" string="(update)" class="oe_link oe_edit_only" type="object" help="Recompute taxes and total" position="replace">
                                     <button name="button_reset_taxes" states="draft,proforma2" string="Compute Taxes" class="oe_link oe_edit_only" type="object" help="Recompute taxes and total"/>
                                 </button>

                                <xpath expr="/form/sheet/group" position="after">
                                    <group colspan="4" col="4" string="Avalara Tax on...">
                                        <group>
                                            <field name="tax_add_default" readonly="1"/>
                                <field name="tax_add_invoice" readonly="1"/>
                                <field name="tax_add_shipping" readonly="1"/>
                                        </group>
                                        <group>
                                            <field name="shipping_address" readonly="1"/>
                                            <!-- <field name="shipping_add_id" context="{'show_address': 1}" 
                                options='{"always_reload": True}' readonly="1"/> -->
                                        </group>
                    </group>
                </xpath>
            </data></field>
        </record>
Traceback (most recent call last):
  File "/home/kinner/workspace/openerp/7.0/server/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/tools/convert.py", line 819, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/kinner/workspace/openerp/7.0/server/openerp/addons/base/ir/ir_model.py", line 971, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/addons/base/ir/ir_ui_view.py", line 103, in create
    return super(view, self).create(cr, uid, values, context)
  File "/home/kinner/workspace/openerp/7.0/openerp-connector/connector/producer.py", line 42, in create
    record_id = create_original(self, cr, uid, vals, context=context)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/orm.py", line 4551, in create
    self._validate(cr, user, [id_new], context)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/orm.py", line 1562, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
except_orm: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')
2014-07-28 12:00:52,294 30466 ERROR faction_20140728 openerp.netsvc: ValidateError
Error occurred while validating the field(s) arch: Invalid XML for View Architecture!
Traceback (most recent call last):
  File "/home/kinner/workspace/openerp/7.0/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/addons/base/module/module.py", line 426, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/addons/base/module/module.py", line 477, in _button_immediate_function
    _, pool = pooler.restart_pool(cr.dbname, update_module=True)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/pooler.py", line 39, in restart_pool
    registry = RegistryManager.new(db_name, force_demo, status, update_module)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/modules/loading.py", line 354, in load_modules
    loaded_modules, update_module)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/modules/loading.py", line 256, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/modules/loading.py", line 187, in load_module_graph
    load_update_xml(module_name, idref, mode)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/modules/loading.py", line 74, in <lambda>
    load_update_xml = lambda *args: _load_data(cr, *args, kind='update_xml')
  File "/home/kinner/workspace/openerp/7.0/server/openerp/modules/loading.py", line 124, in _load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode, noupdate, report)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/tools/convert.py", line 959, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/kinner/workspace/openerp/7.0/server/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/tools/convert.py", line 819, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/kinner/workspace/openerp/7.0/server/openerp/addons/base/ir/ir_model.py", line 971, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/addons/base/ir/ir_ui_view.py", line 103, in create
    return super(view, self).create(cr, uid, values, context)
  File "/home/kinner/workspace/openerp/7.0/openerp-connector/connector/producer.py", line 42, in create
    record_id = create_original(self, cr, uid, vals, context=context)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/orm.py", line 4551, in create
    self._validate(cr, user, [id_new], context)
  File "/home/kinner/workspace/openerp/7.0/server/openerp/osv/orm.py", line 1562, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
except_osv: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')
```

**Comment by kenvac** [comment]
Fixed in new version.
